echo "File Name: $0"
echo "First Parameter : $1"
echo "Second Parameter : $2"
echo "Quoted Values: $@"
echo "Quoted Values: $*"
echo "Total Number of Parameters : $#"
echo "Exit status of last command: $?"
echo "Process number of current shell: $$"
echo "Process number of last background command: $!"
